service: lessons-of-hn-telegram-bot

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    BOT_API_KEY: ${file(./env.json):BOT_API_KEY}
    CHANNEL_ID: ${file(./env.json):CHANNEL_ID}
    API_KEY: ${file(./env.json):FIREBASE.apiKey}
    AUTH_DOMAIN: ${file(./env.json):FIREBASE.authDomain}
    DATABASE_URL: ${file(./env.json):FIREBASE.databaseURL}
    PROJECT_ID: ${file(./env.json):FIREBASE.projectId}
    STORAGE_BUCKET: ${file(./env.json):FIREBASE.storageBucket}
    MESSAGING_SENDER_ID: ${file(./env.json):FIREBASE.messagingSenderId}

functions:
  cron:
    handler: handler.run
    description: Cron job that runs every Sunday at 10 am UTC
    events:
      - schedule: cron(0 10 ? * SUN *)